package com.honghe.recordhibernate.entity;

// Generated 2014-7-30 18:08:49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dtype generated by hbm2java
 */
@Entity
@Table(name = "dtype")
public class Dtype implements java.io.Serializable
{

	private Integer dtypeId;
	private String dtypeName;
	private String dtypeDesc;
	
	private Set<Dspecification> dspecifications = new HashSet<Dspecification>(0);

	public Dtype()
	{
	}

	public Dtype(String dtypeName, String dtypeDesc)
	{
		this.dtypeName = dtypeName;
		this.dtypeDesc = dtypeDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dtype_id", unique = true, nullable = false)
	public Integer getDtypeId()
	{
		return this.dtypeId;
	}

	public void setDtypeId(Integer dtypeId)
	{
		this.dtypeId = dtypeId;
	}

	@Column(name = "dtype_name", length = 50)
	public String getDtypeName()
	{
		return this.dtypeName;
	}

	public void setDtypeName(String dtypeName)
	{
		this.dtypeName = dtypeName;
	}

	@Column(name = "dtype_desc")
	public String getDtypeDesc()
	{
		return this.dtypeDesc;
	}

	public void setDtypeDesc(String dtypeDesc)
	{
		this.dtypeDesc = dtypeDesc;
	}
	
	//*******************************************

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dtype")
	public Set<Dspecification> getDspecifications()
	{
		return this.dspecifications;
	}

	public void setDspecifications(Set<Dspecification> dspecifications)
	{
		this.dspecifications = dspecifications;
	}

}
