package com.honghe.recordhibernate.entity;

// Generated 2014-7-30 18:08:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Command generated by hbm2java
 */
@Entity
@Table(name = "command")
public class Command implements java.io.Serializable
{

	private Integer cmdId;
	private String cmdName;
	private String cmdGroup;
	private Integer cmdDefault;
    private String cmdFlag;
    private String cmdHex;
    private String cmdImage;
	
	//one2many
    private Set<Spec2command> spec2command = new HashSet<Spec2command>(0);
	/*many2many*/
//	private Set<Dspecification> dspecifications = new HashSet<Dspecification>(0);

	public Command()
	{
	}

	public Command(String cmdName, String cmdGroup, Integer cmdDefault)
	{
		this.cmdName = cmdName;
		this.cmdGroup = cmdGroup;
		this.cmdDefault = cmdDefault;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cmd_id", unique = true, nullable = false)
	public Integer getCmdId()
	{
		return this.cmdId;
	}

	public void setCmdId(Integer cmdId)
	{
		this.cmdId = cmdId;
	}

	@Column(name = "cmd_name", length = 50)
	public String getCmdName()
	{
		return this.cmdName;
	}

	public void setCmdName(String cmdName)
	{
		this.cmdName = cmdName;
	}

	@Column(name = "cmd_group", length = 50)
	public String getCmdGroup()
	{
		return this.cmdGroup;
	}

	public void setCmdGroup(String cmdGroup)
	{
		this.cmdGroup = cmdGroup;
	}

	@Column(name = "cmd_default")
	public Integer getCmdDefault()
	{
		return this.cmdDefault;
	}

	public void setCmdDefault(Integer cmdDefault)
	{
		this.cmdDefault = cmdDefault;
	}

    @Column(name = "cmd_flag")
    public String getCmdFlag()
    {
        return this.cmdFlag;
    }

    public void setCmdFlag(String cmdFlag)
    {
        this.cmdFlag = cmdFlag;
    }

    @Column(name = "cmd_hex")
    public String getCmdHex()
    {
        return this.cmdHex;
    }

    public void setCmdHex(String cmdHex)
    {
        this.cmdHex = cmdHex;
    }

    @Column(name = "cmd_image")
    public String getCmdImage()
    {
        return this.cmdImage;
    }

    public void setCmdImage(String cmdImage)
    {
        this.cmdImage = cmdImage;
    }
	
	//*******************************************

	@OneToMany(mappedBy="command",  fetch = FetchType.LAZY)
	public Set<Spec2command> getSpec2command()
	{
		return this.spec2command;
	}

	public void setSpec2command(Set<Spec2command> spec2command)
	{
		this.spec2command = spec2command;
	}
}
