package com.honghe.recordhibernate.entity;

// Generated 2014-7-30 18:08:49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Hostgroup generated by hbm2java
 */
@Entity
@Table(name = "hostgroup")
public class Hostgroup implements java.io.Serializable
{

	private Integer groupId;
	private String groupName;
	
	/*many2many*/
	private Set<Host> hosts = new HashSet<Host>(0);

	private Set<User> users = new HashSet<User>(0);	

	public Hostgroup()
	{
	}

	public Hostgroup(String groupName)
	{
		this.groupName = groupName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "group_id", unique = true, nullable = false)
	public Integer getGroupId()
	{
		return this.groupId;
	}

	public void setGroupId(Integer groupId)
	{
		this.groupId = groupId;
	}

	@Column(name = "group_name", length = 50)
	public String getGroupName()
	{
		return this.groupName;
	}

	public void setGroupName(String groupName)
	{
		this.groupName = groupName;
	}

	//*******************************************

//	@ManyToMany
//	@JoinTable(name = "group2host", joinColumns =
//	{ @JoinColumn(name = "group_id") }, inverseJoinColumns =
//	{ @JoinColumn(name = "host_id") })
//    @ManyToMany(targetEntity=Host.class,mappedBy="hostgroups",fetch = FetchType.LAZY)
	@Transient
	public Set<Host> getHosts()
	{
		return this.hosts;
	}

	public void setHosts(Set<Host> hosts)
	{
		this.hosts = hosts;
	}
	@Transient
//	@ManyToMany(targetEntity=User.class,mappedBy="hostgroups",fetch = FetchType.LAZY)
	public Set<User> getUsers()
	{
		return this.users;
	}

	public void setUsers(Set<User> users)
	{
		this.users = users;
	}
}
