package com.honghe.recordhibernate.entity;

// Generated 2014-7-30 18:08:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "setting_nas")
public class Nas implements java.io.Serializable {

    private Integer NasId;

    private String NasRootpath;

//    private Set<Host> hosts;
//
//    @ManyToMany(fetch = FetchType.LAZY)
//    @JoinTable(name = "nas2host", joinColumns =
//            {@JoinColumn(name = "nas_id")}, inverseJoinColumns =
//            {@JoinColumn(name = "host_id")})
//    public Set<Host> getHosts() {
//        return hosts;
//    }
//
//    public void setHosts(Set<Host> hosts) {
//        this.hosts = hosts;
//    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "nas_id", unique = true, nullable = false)
    public Integer getNasId() {
        return NasId;
    }

    public void setNasId(Integer nasId) {
        NasId = nasId;
    }


    @Column(name = "nas_rootpath")
    public String getNasRootpath() {
        return NasRootpath;
    }

    public void setNasRootpath(String nasRootpath) {
        NasRootpath = nasRootpath;
    }

    @Column(name = "nas_username")
    public String getNasUsername() {
        return NasUsername;
    }

    public void setNasUsername(String nasUsername) {
        NasUsername = nasUsername;
    }

//    @Column(name = "nas_filepath")
//    public String getNasFilepath() {
//        return NasFilepath;
//    }
//
//    public void setNasFilepath(String nasFilepath) {
//        NasFilepath = nasFilepath;
//    }

    @Column(name = "nas_password")
    public String getNasPassword() {
        return NasPassword;
    }

    public void setNasPassword(String nasPassword) {
        NasPassword = nasPassword;
    }

//    private String NasFilepath;
    private String NasUsername;
    private String NasPassword;

}
