package com.honghe.recordhibernate.entity;

// Generated 2014-7-30 18:08:49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */

public class Role implements java.io.Serializable
{

	private Integer roleId;
	private String roleName;
	
	/*many2many*/
	private Set<User> users = new HashSet<User>(0);
	private Set<Authority> authortys = new HashSet<Authority>(0);

	public Role()
	{
	}

	public Role(String roleName)
	{
		this.roleName = roleName;
	}


	public Integer getRoleId()
	{
		return this.roleId;
	}

	public void setRoleId(Integer roleId)
	{
		this.roleId = roleId;
	}


	public String getRoleName()
	{
		return this.roleName;
	}

	public void setRoleName(String roleName)
	{
		this.roleName = roleName;
	}

	//*******************************************
	

	public Set<User> getUsers()
	{
		return this.users;
	}

	public void setUsers(Set<User> users)
	{
		this.users = users;
	}
	

	public Set<Authority> getAuthoritys()
	{
		return this.authortys;
	}
	
	public void setAuthoritys(Set<Authority> authortys)
	{
		this.authortys = authortys;
	} 
}
