package com.honghe.recordhibernate.entity;

// Generated 2014-8-1 10:18:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Spec2command generated by hbm2java
 */
@Entity
@Table(name = "spec2command")
public class Spec2command implements java.io.Serializable
{

	private Integer t2cId;
//	private Integer dspecId;
//	private Integer cmdId;
	private String cmdWord;
	private String cmdParam;
	private String cmdReturn;
	private String cmdFlag;
	
	//one2one

	//many2one
    private Command command;
	private Dspecification dspecification;

	public Spec2command()
	{
	}

	public Spec2command(String cmdWord,
			String cmdParam, String cmdReturn, String cmdFlag)
	{
		this.cmdWord = cmdWord;
		this.cmdParam = cmdParam;
		this.cmdReturn = cmdReturn;
		this.cmdFlag = cmdFlag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "t2c_id", unique = true, nullable = false)
	public Integer getT2cId()
	{
		return this.t2cId;
	}

	public void setT2cId(Integer t2cId)
	{
		this.t2cId = t2cId;
	}

	@Column(name = "cmd_word")
	public String getCmdWord()
	{
		return this.cmdWord;
	}

	public void setCmdWord(String cmdWord)
	{
		this.cmdWord = cmdWord;
	}

	@Column(name = "cmd_param")
	public String getCmdParam()
	{
		return this.cmdParam;
	}

	public void setCmdParam(String cmdParam)
	{
		this.cmdParam = cmdParam;
	}

	@Column(name = "cmd_return")
	public String getCmdReturn()
	{
		return this.cmdReturn;
	}

	public void setCmdReturn(String cmdReturn)
	{
		this.cmdReturn = cmdReturn;
	}

	@Column(name = "cmd_flag", length = 2)
	public String getCmdFlag()
	{
		return this.cmdFlag;
	}

	public void setCmdFlag(String cmdFlag)
	{
		this.cmdFlag = cmdFlag;
	}

	//*******************************************
	
	@ManyToOne
	@JoinColumn(name="cmd_id")
	public Command getCommand()
	{
		return this.command;
	}

	public void setCommand(Command command)
	{
		this.command = command;
	}
	
	@ManyToOne
	@JoinColumn(name="dspec_id")
	public Dspecification getDspecification()
	{
		return this.dspecification;
	}
	
	public void setDspecification(Dspecification dspecification)
	{
		this.dspecification = dspecification;
	}
}
