package com.honghe.recordhibernate.entity;

// Generated 2014-7-30 18:08:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * User generated by hbm2java
 */

public class User implements java.io.Serializable {

    private Integer userId;
    private String userName;
    private String userPwd;
    private String schoolName;
    private String userDesc;

    private String user_salt;
    private String userAddress; //地址
    private String userGender; //性别 1男2女
    private String userMobile; //手机号
    private String userEmail;// 邮箱

    private String userAvatar; //头像图片名称
    private String userRealName; // 真实姓名
    private String userPath; //头像存放路径
    private String userRegdate; //注册时间
    private String userBirthday; // 出生日

    private String userType; //用户类型 1-老师 2-学生 3-家长 4-管理员


    /*many2many*/
    private Set<Hostgroup> hostgroups = new HashSet<Hostgroup>(0);
    private Set<Role> roles = new HashSet<Role>(0);

	/*one2many*/
//	private Set<Applog> applogs = new HashSet<Applog>(0);

    public User() {
    }

    public User(Map<String,String> value){

        if(value !=null){
            userId = Integer.valueOf(value.get("userId"));
            userName = value.get("userName");
            userPwd = value.get("userPwd");
            schoolName ="";
            userDesc ="";

            user_salt="";
            userAddress = value.get("userAddress");
            userGender = value.get("userGender");
            userMobile = value.get("userMobile");
            userEmail =value.get("userEmail");

            userAvatar =value.get("userAvatar");
            userRealName = value.get("userRealName");
            userPath = value.get("userPath");
            userRegdate = value.get("userRegdate");
            userBirthday = value.get("userBirthday");

            userType = value.get("userType");

           user_salt = userType.equals("4")?"true":"false";
        }

    }


    public User(String userName, String userPwd) {
        this.userName = userName;
        this.userPwd = userPwd;
    }

    public User(String userName, String userPwd, String schoolName,
                String userDesc) {
        this.userName = userName;
        this.userPwd = userPwd;
        this.schoolName = schoolName;
        this.userDesc = userDesc;
    }


    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }


    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }


    public String getUserPwd() {
        return this.userPwd;
    }

    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }


    public String getSchoolName() {
        return this.schoolName;
    }

    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }


    public String getUserDesc() {
        return this.userDesc;
    }

    public void setUserDesc(String userDesc) {
        this.userDesc = userDesc;
    }

    //*******************************************


    public Set<Hostgroup> getHostgroups() {
        return this.hostgroups;
    }

    public void setHostgroups(Set<Hostgroup> hostgroups) {
        this.hostgroups = hostgroups;
    }


    public Set<Role> getRoles() {
        return this.roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

    public String getUser_salt() {
        return user_salt;
    }

    public void setUser_salt(String user_salt) {
        this.user_salt = user_salt;
    }
//	@OneToMany(mappedBy="user", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
//	//@JoinColumn(name = "user_id", updatable=false)
//	public Set<Applog> getApplogs()
//	{
//		return this.applogs;
//	}
//
//	public void setApplogs(Set<Applog> applogs)
//	{
//		this.applogs = applogs;
//	}


    public String getUserAddress() {
        return userAddress;
    }

    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    public String getUserGender() {
        return userGender;
    }

    public void setUserGender(String userGender) {
        this.userGender = userGender;
    }

    public String getUserMobile() {
        return userMobile;
    }

    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile;
    }

    public String getUserEmail() {
        return userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getUserAvatar() {
        return userAvatar;
    }

    public void setUserAvatar(String userAvatar) {
        this.userAvatar = userAvatar;
    }

    public String getUserRealName() {
        return userRealName;
    }

    public void setUserRealName(String userRealName) {
        this.userRealName = userRealName;
    }

    public String getUserPath() {
        return userPath;
    }

    public void setUserPath(String userPath) {
        this.userPath = userPath;
    }

    public String getUserRegdate() {
        return userRegdate;
    }

    public void setUserRegdate(String userRegdate) {
        this.userRegdate = userRegdate;
    }

    public String getUserBirthday() {
        return userBirthday;
    }

    public void setUserBirthday(String userBirthday) {
        this.userBirthday = userBirthday;
    }

    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }
}
