package com.honghe.recordhibernate.entity;

// Generated 2014-7-30 18:08:49 by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Host generated by hbm2java
 */

public class Host implements java.io.Serializable
{

	private Integer hostId;

	private String hostName;
	private String hostIpaddr;
	private String hostSerialno;
	private String hostDesc;
    private String hostUserName;

	private String hostPassWord;


	public String getHostMac() {
		return hostMac;
	}

	public void setHostMac(String hostMac) {
		this.hostMac = hostMac;
	}

	private String hostMac;

	

	private Set<Hostgroup> hostgroups = new HashSet<Hostgroup>(0);
	/*many2one*/
	private Dspecification dspecification;
    /*oneToMany*/
//    private Set<Timeplan> timeplan;
	/*manyToMany*/
	private Set<News> newsSet;
    /*manyToMany*/
    private Set<Policy> policySet = new HashSet<Policy>(0);
	//add by xinye
	private Set<Temporaryplan> temporaryplanSet = new HashSet<>();
	//add by xinye end
	public Host()
	{
	}

	public Host( String hostName, String hostIpaddr,
			String hostSerialno, String hostDesc)
	{
	
		this.hostName = hostName;
		this.hostIpaddr = hostIpaddr;
		this.hostSerialno = hostSerialno;
		this.hostDesc = hostDesc;
	}


	public Integer getHostId()
	{
		return this.hostId;
	}

	public void setHostId(Integer hostId)
	{
		this.hostId = hostId;
	}

	


	public String getHostName()
	{
		return this.hostName;
	}

	public void setHostName(String hostName)
	{
		this.hostName = hostName;
	}


	public String getHostIpaddr()
	{
		return this.hostIpaddr;
	}

	public void setHostIpaddr(String hostIpaddr)
	{
		this.hostIpaddr = hostIpaddr;
	}


	public String getHostSerialno()
	{
		return this.hostSerialno;
	}

	public void setHostSerialno(String hostSerialno)
	{
		this.hostSerialno = hostSerialno;
	}


	public String getHostDesc()
	{
		return this.hostDesc;
	}

	public void setHostDesc(String hostDesc)
	{
		this.hostDesc = hostDesc;
	}


    public String getHostUserName()
    {
        return this.hostUserName;
    }

    public void setHostUserName(String hostUserName)
    {
        this.hostUserName = hostUserName;
    }


    public String getHostPassWord()
    {
        return this.hostPassWord;
    }

    public void setHostPassWord(String hostPassWord)
    {
        this.hostPassWord = hostPassWord;
    }




	public Dspecification getDspecification()
	{
		return this.dspecification;
	}
	
	public void setDspecification(Dspecification dspecification)
	{
		this.dspecification = dspecification;
	}


	public Set<Hostgroup> getHostgroups()
	{
		return this.hostgroups;
	}
	
	public void setHostgroups(Set<Hostgroup> hostgroups)
	{
		this.hostgroups = hostgroups;
	}

  /*  @OneToMany(fetch = FetchType.LAZY,mappedBy="host",targetEntity=Timeplan.class)
    public Set<Timeplan> getTimeplan() {
        return timeplan;
    }

    public void setTimeplan(Set<Timeplan> timeplan) {
        this.timeplan = timeplan;
    }*/


    public Set<Policy> getPolicySet()
    {
        return this.policySet;
    }

    public void setPolicySet(Set<Policy> policySet)
    {
        this.policySet = policySet;
    }

	//add by xinye

	public Set<Temporaryplan> getTemporaryplanSet() {
		return temporaryplanSet;
	}

	public void setTemporaryplanSet(Set<Temporaryplan> temporaryplanSet) {
		this.temporaryplanSet = temporaryplanSet;
	}

	//add by xinye end
}
