package com.honghe.recordhibernate.entity;

// Generated 2014-7-30 18:08:49 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * device generated by hbm2java
 */
@Entity
@Table(name = "device")
public class Device implements java.io.Serializable {

    private Integer deviceId;
    private String deviceName;

    //	private Integer dspecId;
//	private Integer hostId;
    @Column(name = "device_subtoken")
    public String getDeviceSubToken() {
        return deviceSubToken;
    }

    public void setDeviceSubToken(String deviceSubToken) {
        this.deviceSubToken = deviceSubToken;
    }

    private Integer hostId;
    private String deviceMainToken;
    private String deviceSubToken;
    private String deviceMainStream;
    @Column(name = "device_mainstream")
    public String getDeviceMainStream() {
        return deviceMainStream;
    }

    public void setDeviceMainStream(String deviceMainStream) {
        this.deviceMainStream = deviceMainStream;
    }
    @Column(name = "device_substream")
    public String getDeviceSubStream() {
        return deviceSubStream;
    }

    public void setDeviceSubStream(String deviceSubStream) {
        this.deviceSubStream = deviceSubStream;
    }

    private String deviceSubStream;


    public Device() {
    }

    public Device(String deviceName) {
        this.deviceName = deviceName;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "device_id", unique = true, nullable = false)
    public Integer getDeviceId() {
        return this.deviceId;
    }

    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    @Column(name = "device_name", length = 50)
    public String getDeviceName() {
        return this.deviceName;
    }

    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }

//	@Column(name = "dspec_id")
//	public Integer getDspecId()
//	{
//		return this.dspecId;
//	}
//
//	public void setDspecId(Integer dspecId)
//	{
//		this.dspecId = dspecId;
//	}

//	@Column(name = "host_id")
//	public Integer getHostId()
//	{
//		return this.hostId;
//	}
//
//	public void setHostId(Integer hostId)
//	{
//		this.hostId = hostId;
//	}

    @Column(name = "device_maintoken")
    public String getDeviceMainToken() {
        return deviceMainToken;
    }

    public void setDeviceMainToken(String token) {
        this.deviceMainToken = token;
    }

    @Column(name = "host_id")
    public Integer getHostId() {
        return hostId;
    }

    public void setHostId(Integer hostId) {
        this.hostId = hostId;
    }
}
