package com.honghe.recordhibernate.entity;

// Generated 2014-7-30 18:08:49 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Authority generated by hbm2java
 */
@Entity
@Table(name = "authority")
public class Authority implements java.io.Serializable
{

	private Integer authId;
	private String authWord;
	private String authName;
	private String authDesc;
    private Integer authRange;
	
	/*many2many*/
	private Set<Role> roles = new HashSet<Role>(0);
	
	

	public Authority()
	{
	}

	public Authority(String authWord, String authName, String authDesc,Integer authRange)
	{
		this.authWord = authWord;
		this.authName = authName;
		this.authDesc = authDesc;
        this.authRange = authRange;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "auth_id", unique = true, nullable = false)
	public Integer getAuthId()
	{
		return this.authId;
	}

	public void setAuthId(Integer authId)
	{
		this.authId = authId;
	}

	@Column(name = "auth_word", length = 50)
	public String getAuthWord()
	{
		return this.authWord;
	}

	public void setAuthWord(String authWord)
	{
		this.authWord = authWord;
	}

	@Column(name = "auth_name", length = 50)
	public String getAuthName()
	{
		return this.authName;
	}

	public void setAuthName(String authName)
	{
		this.authName = authName;
	}

	@Column(name = "auth_desc")
	public String getAuthDesc()
	{
		return this.authDesc;
	}

    public void setAuthDesc(String authDesc)
    {
        this.authDesc = authDesc;
    }

    @Column(name = "auth_range")
    public Integer getAuthRange()
    {
        return this.authRange;
    }

    public void setAuthRange(Integer authRange)
    {
        this.authRange = authRange;
    }



	//*******************************************
	
//	@ManyToMany(targetEntity=Role.class)
//	@JoinTable(name = "role2authority", joinColumns =
//	{ @JoinColumn(name = "auth_id") }, inverseJoinColumns =
//	{ @JoinColumn(name = "role_id") })
	@Transient
	public Set<Role> getRoles()
	{
		return this.roles;
	}
	
	public void setRoles(Set<Role> roles)
	{
		this.roles = roles;
	}
}
